/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author LENOVO
 */
public class UI_Informe extends javax.swing.JPanel {

    /**
     * Creates new form UI_Informe
     */
    public UI_Informe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new Styles.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        datePick = new Styles.DatePickerCustom();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        atxtDescripcion = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblInformes = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        panelRound2 = new Styles.PanelRound();
        jLabel7 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cbxEstado = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cbxAccionesTomadas = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cbxIncidencias = new javax.swing.JComboBox<>();
        cbxPersonal = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(245, 246, 250));

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setPreferredSize(new java.awt.Dimension(878, 463));
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Informe de Incidencias Informáticas");
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        panelRound1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 20, -1, -1));

        jLabel3.setText("Acciones Tomadas");
        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        panelRound1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 70, -1, -1));
        panelRound1.add(datePick, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 90, 221, 31));

        jLabel4.setText("Fecha de resolución");
        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        panelRound1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 70, -1, -1));

        atxtDescripcion.setColumns(20);
        atxtDescripcion.setRows(5);
        atxtDescripcion.setPreferredSize(new java.awt.Dimension(232, 74));
        jScrollPane1.setViewportView(atxtDescripcion);

        panelRound1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 238, 247, 230));

        jLabel5.setText("Descripcion de la solución");
        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        panelRound1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 247, 31));

        btnRegistrar.setText("Registrar");
        btnRegistrar.setBackground(new java.awt.Color(153, 0, 51));
        btnRegistrar.setBorderPainted(false);
        btnRegistrar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        panelRound1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 150, 126, 31));

        btnConsultar.setText("Consultar");
        btnConsultar.setBackground(new java.awt.Color(0, 121, 153));
        btnConsultar.setBorderPainted(false);
        btnConsultar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        panelRound1.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 150, 126, 31));

        btnActualizar.setText("Actualizar");
        btnActualizar.setBackground(new java.awt.Color(68, 23, 38));
        btnActualizar.setBorderPainted(false);
        btnActualizar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        panelRound1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 150, 126, 31));

        tblInformes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Acciones Tomadas", "Estado", "Personal", "Descripción", "Fecha"
            }
        ));
        jScrollPane2.setViewportView(tblInformes);

        panelRound1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 187, 645, 290));

        jSeparator1.setForeground(new java.awt.Color(153, 0, 51));
        panelRound1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 130, 645, 10));

        panelRound2.setBackground(new java.awt.Color(0, 153, 51));
        panelRound2.setRoundBottomLeft(20);
        panelRound2.setRoundBottomRight(20);
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("#CAT-0001");
        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        panelRound1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 20, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.setBackground(new java.awt.Color(255, 153, 0));
        btnEliminar.setBorderPainted(false);
        btnEliminar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        panelRound1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 150, 111, 31));

        jLabel6.setText("Estado");
        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        panelRound1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 70, -1, -1));

        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Seleccionar]", "EN PROCESO", "ATENDIDO", "DERIVADO" }));
        cbxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEstadoActionPerformed(evt);
            }
        });
        panelRound1.add(cbxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 90, 250, 30));

        jLabel8.setText("ID de incidencia ");
        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        panelRound1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        cbxAccionesTomadas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Seleccionar]", "Actualización de Hardware", "Actualización de Software", "Reinicio de Sistema", "Corrección de Configuración", "Restablecimiento de Red", "Optimización de Rendimiento" }));
        cbxAccionesTomadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAccionesTomadasActionPerformed(evt);
            }
        });
        panelRound1.add(cbxAccionesTomadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 90, 241, 31));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel9.setText("Personal a cargo");
        panelRound1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, -1, -1));

        cbxIncidencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxIncidenciasActionPerformed(evt);
            }
        });
        panelRound1.add(cbxIncidencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 160, 30));

        cbxPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPersonalActionPerformed(evt);
            }
        });
        panelRound1.add(cbxPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 162, 240, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEstadoActionPerformed

    private void cbxAccionesTomadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAccionesTomadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxAccionesTomadasActionPerformed

    private void cbxIncidenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxIncidenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxIncidenciasActionPerformed

    private void cbxPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPersonalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea atxtDescripcion;
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnConsultar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnRegistrar;
    public javax.swing.JComboBox<String> cbxAccionesTomadas;
    public javax.swing.JComboBox<String> cbxEstado;
    public javax.swing.JComboBox<Model.Incidencias> cbxIncidencias;
    public javax.swing.JComboBox<Model.Personal> cbxPersonal;
    public Styles.DatePickerCustom datePick;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private Styles.PanelRound panelRound1;
    private Styles.PanelRound panelRound2;
    public javax.swing.JTable tblInformes;
    // End of variables declaration//GEN-END:variables
}
